# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# now alias $(now) thing
version: 2
general:
  branches:
    only:
      - master # list of branches to build
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Install globals
      - run: sudo npm i -g now --unsafe-perm
      
      # BACKEND STUFF
      - run: cd app-backend && yarn install
      - run: cd app-backend && now alias $(now --force --token=$NOW_TOKEN -e ENV=production -e MLAB_API_KEY=$MLAB_API_KEY) --token=$NOW_TOKEN
      - run: y | now rm api.erasmoose.com --safe --token=$NOW_TOKEN
                     
      # FRONTEND STUFF
      - run: cd app-client && yarn install
      - run: cd app-client && now alias $(now --force --token=$NOW_TOKEN -e ENV=production -e SERVER_URL=$SERVER_URL) --token=$NOW_TOKEN
      - run: y | now rm erasmoose.com --safe --token=$NOW_TOKEN